dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: test
      name: "Tests"
      script: make test
    - stage: scan
      name: "Security Scan"
      script: skip
    - stage: deploy
      if: branch = master
      name: "Deploy to Production"
      script: skip
